// Command semanticgen compiles the reviewable semantic lexicon into a compact
// Go table. Runtime analysis never parses the source JSON or scans WordNet.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strconv"
)

type sourceLexicon struct {
	Version  int             `json:"version"`
	Concepts []sourceConcept `json:"concepts"`
}

type sourceConcept struct {
	ID          string   `json:"id"`
	Phrases     []string `json:"phrases"`
	Definitions []string `json:"definitions"`
}

func main() {
	input := flag.String("input", "semantic/lexicon.json", "source lexicon")
	output := flag.String("output", "sos/semantic_lexicon_generated.go", "generated Go file")
	flag.Parse()

	raw, err := os.ReadFile(*input)
	if err != nil {
		fatal(err)
	}
	var src sourceLexicon
	if err := json.Unmarshal(raw, &src); err != nil {
		fatal(err)
	}
	if src.Version < 1 {
		fatal(fmt.Errorf("lexicon version must be positive"))
	}
	sort.Slice(src.Concepts, func(i, j int) bool { return src.Concepts[i].ID < src.Concepts[j].ID })

	var out bytes.Buffer
	fmt.Fprintln(&out, "// Code generated by cmd/semanticgen; DO NOT EDIT.")
	fmt.Fprintln(&out, "package sos")
	fmt.Fprintf(&out, "\nconst semanticLexiconVersion = %d\n", src.Version)
	fmt.Fprintln(&out, "\nvar generatedSemanticConcepts = []semanticConcept{")
	for _, concept := range src.Concepts {
		if concept.ID == "" || len(concept.Phrases) == 0 || len(concept.Definitions) == 0 {
			fatal(fmt.Errorf("concepts require id, phrases, and definitions: %+v", concept))
		}
		sort.Strings(concept.Phrases)
		sort.Strings(concept.Definitions)
		fmt.Fprintf(&out, "\t{ID: %s, Phrases: []string{", strconv.Quote(concept.ID))
		for i, phrase := range concept.Phrases {
			if i > 0 {
				fmt.Fprint(&out, ", ")
			}
			fmt.Fprint(&out, strconv.Quote(phrase))
		}
		fmt.Fprint(&out, "}, Definitions: []string{")
		for i, definition := range concept.Definitions {
			if i > 0 {
				fmt.Fprint(&out, ", ")
			}
			fmt.Fprint(&out, strconv.Quote(definition))
		}
		fmt.Fprintln(&out, "}},")
	}
	fmt.Fprintln(&out, "}")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*output, formatted, 0o644); err != nil {
		fatal(err)
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "semanticgen:", err)
	os.Exit(1)
}
